pull_request_rules:
  - name: Automatic merge on Green CI (required tests only)
    conditions:
      - check-success=checkfilesize
      - check-success=build-site-test-links
    actions:
      merge:
        method: merge
