pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=checkfilesize
      - check-success=build-site-test-links
      - check-success=spellcheck
    actions:
      merge:
        method: merge
