pull_request_rules:
  - name: Automatic merge on Green CI (required tests only)
    conditions:
      - check-success=checkfilesize
      - check-success=build-and-deploy
      - check-success=spellcheck
      - check-success=linkcheck
      - label!=work-in-progress
    actions:
      merge:
        method: merge
