name: CI Tests

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  checkfilesize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check for large files
        working-directory: ./images
        run: |
          echo "Performing file size check..."
          BIG_FILES=$(find . -size +5M -name ! -path "./.git/*" -print)
          if [ -n "$BIG_FILES" ] ; then
            echo "Uh-oh! Large files found!"
            echo "$BIG_FILES" 1>&2
            exit 1
          else
            echo "No large files found!"
          fi

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Perform Spellcheck
        uses: UnicornGlobal/spellcheck-github-actions@master

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build site with Jekyll
        uses: lemonarc/jekyll-action@1.0.0

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: --only-4xx --check-favicon --check-html --assume-extension --empty-alt-ignore --disable-external
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
