name: Check for broken links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.108.0"
 
      - name: Build
        run: hugo --minify --enableGitInfo

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          # Exclude linkedin.com: Returns "too many requests" error
          # Exclude turing.ac.uk: Always returns a 403
          args: >-
            --exclude https://linkedin.com
            --exclude https://www.turing.ac.uk
            --verbose
            --no-progress
            public/**/*.html
          # Fail action on broken links in Pull Requests
          fail: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add lychee failures to issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Linkcheck Report
          content-filepath: ./lychee/out.md
          labels: bug, website
          issue-number: 232

      - name: Clear issue when there are no lychee failures
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: "2321496400"
          body: |
            **No broken links found!**
          edit-mode: replace
