name: Check for broken links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.108.0"
 
      - name: Build
        run: hugo --minify --enableGitInfo

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          # Exclude linkedin.com: Returns "too many requests" error
          args: >-
            --exclude https://linkedin.com
            --verbose
            --no-progress
            public/**/*.html
          # Fail action on broken links in Pull Requests
          fail: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create issue from file
      #   if: env.lychee_exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v4
      #   with:
      #     title: Linkcheck Report
      #     content-filepath: ./lychee/out.md
      #     labels: bug, website
