name: Spellcheck

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Perform Spellcheck
        uses: UnicornGlobal/spellcheck-github-actions@master
