name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkfilesize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Check for large files
        working-directory: ./static
        run: |
          echo "Performing file size check..."
          BIG_FILES=$(find . -size +5M -name ! -path "./.git/*" -print)
          if [ -n "$BIG_FILES" ] ; then
            echo "Uh-oh! Large files found!"
            echo "$BIG_FILES" 1>&2
            exit 1
          else
            echo "No large files found!"
          fi

  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0

      - name: Install markdown-spellcheck
        run: |
          npm i markdown-spellcheck -g

      - name: Run spellcheck on Markdown files
        run: |
          mdspell --ignore-numbers --ignore-acronyms --en-gb --report \
            CODE_OF_CONDUCT.md \
            CONTRIBUTING.md \
            README.md \
            "content/**/*.md"
