name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkfilesize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for large files
        working-directory: ./static
        run: |
          echo "Performing file size check..."
          BIG_FILES=$(find . -size +5M -name ! -path "./.git/*" -print)
          if [ -n "$BIG_FILES" ] ; then
            echo "Uh-oh! Large files found!"
            echo "$BIG_FILES" 1>&2
            exit 1
          else
            echo "No large files found!"
          fi
